// Real renderer, synthetic Electron IPC. No inventory file, cloud, or external network writes.
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import {createServer} from 'vite';
import react from '@vitejs/plugin-react';
const root=process.cwd(),output=path.resolve('test-results/shop-price-ui'),sha=b=>createHash('sha256').update(b).digest('hex');
const sources=['src/renderer/ShopEditor.tsx','src/renderer/shopPriceDraft.ts','src/renderer/cardPriceDraft.ts','src/renderer/main.tsx','src/renderer/cloud.css'];
const sourceFiles=await Promise.all(sources.map(async name=>({path:name,sha256:sha(await readFile(name))})));
const report={passed:false,syntheticIpc:true,realWrites:0,remoteWrites:0,sourceFiles,sourceUnchanged:false,checks:[],errors:[],blocked:[],screenshots:[]};await mkdir(output,{recursive:true});
const server=await createServer({configFile:false,root:path.resolve('src/renderer'),plugins:[react()],server:{host:'127.0.0.1',port:0,fs:{allow:[root]}}});await server.listen();const origin=server.resolvedUrls.local[0];
// Use an installed Playwright package, or an explicitly supplied test runtime.
const runtime=await import(process.env.AMANE_PLAYWRIGHT_MODULE ? pathToFileURL(path.resolve(process.env.AMANE_PLAYWRIGHT_MODULE)).href : 'playwright');
const browser=await(runtime.default||runtime).chromium.launch({channel:process.env.AMANE_BROWSER_CHANNEL || (process.platform === 'win32' ? 'msedge' : undefined),headless:true}),context=await browser.newContext({viewport:{width:1280,height:1000}}),page=await context.newPage();
const check=name=>{report.checks.push({name,passed:true});console.log('PASS '+name);};
page.on('pageerror',e=>report.errors.push(e.message));await context.route('**/*',route=>{const r=route.request();if(new URL(r.url()).origin!==new URL(origin).origin||!['GET','HEAD'].includes(r.method())){report.blocked.push(r.method()+' '+r.url());return route.abort();}return route.continue();});
await context.addInitScript(()=>{
 const stamp='2026-09-23T12:00:00Z',image='12345678-1234-4234-8234-123456789012';
 const item={barcode:'123',createdAt:stamp,updatedAt:stamp,nickname:'晴空徽章',lookupName:'相遇纪念',brand:'',category:'',imageUrl:'',sortIndex:0,listed:false,shop:{imageId:image,originalCents:2000,currentCents:1500,discountBps:2500,priceSource:'current'},priceAmount:4,salePriceAmount:15,priceCurrency:'CAD',lookupSource:'none',lookupConfidence:0,quantityOnHand:10,totalIn:10,totalOut:0,firstInAt:stamp,lastInAt:stamp,lastOutAt:null,lookupStatus:'idle',lookupUpdatedAt:null};
 const initial={filePath:'C:/synthetic/first.json',fileName:'first.json',inventory:{schemaVersion:7,inventoryId:'first',inventoryName:'合成价格验收',createdAt:stamp,updatedAt:stamp,items:{'123':item},transactions:[]}};
 const listeners=new Set(),cloudListeners=new Set(),clone=structuredClone;
 window.qa={document:clone(initial),calls:[],fail:false,defer:false,pending:null,applyCount:0,cloud:{state:'synced',message:'合成云状态',inventoryId:'first',registeredBarcodes:[],shopOperationsSupported:true,account:{id:'synthetic',permissions:['inventory.manage','products.manage','pricing.manage']},secureStorage:true,connected:true,pending:false,lastSuccess:null},emit(patch){Object.assign(this.document.inventory.items['123'],patch);for(const f of listeners)f(clone(this.document));},cloudEmit(patch){Object.assign(this.cloud,patch);for(const f of cloudListeners)f(clone(this.cloud));},switchFile(){this.document=clone(initial);this.document.filePath='C:/synthetic/second.json';this.document.fileName='second.json';this.document.inventory.inventoryId='second';for(const f of listeners)f(clone(this.document));this.cloudEmit({inventoryId:'second',registeredBarcodes:[]});}};
 const qa=window.qa,save=async value=>{if(qa.fail)throw Error('合成磁盘保存失败');if(qa.defer)return new Promise(resolve=>{qa.pending=()=>resolve(clone(value));});qa.document=clone(value);return clone(value);};
 window.amaneStock={getCurrentInventory:async()=>clone(qa.document),getVersion:async()=>'QA',onInventoryChanged:f=>(listeners.add(f),()=>listeners.delete(f)),cloudStatus:async()=>clone(qa.cloud),onCloudStatus:f=>(cloudListeners.add(f),()=>cloudListeners.delete(f)),getShopImage:async()=> 'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',chooseShopImage:async()=>({dataUrl:'data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7',width:1,height:1}),
  updateShop:async(barcode,shop)=>{qa.calls.push({kind:'shop',barcode,shop:clone(shop)});const next=clone(qa.document),item=next.inventory.items[barcode];item.shop=clone(shop);if(item.priceCurrency==='CAD')item.salePriceAmount=shop.currentCents/100;return save(next);},
  updateListing:async(barcode,listed)=>{qa.calls.push({kind:'listing',barcode,listed});const next=clone(qa.document);next.inventory.items[barcode].listed=listed;return save(next);},
  uploadShopImage:async(barcode,dataUrl,crop)=>{qa.calls.push({kind:'image',barcode,dataUrl,crop});const next=clone(qa.document);next.inventory.items[barcode].shop.imageId='22222222-2222-4222-8222-222222222222';return save(next);},
  uploadShopImageAsset:async(dataUrl,crop)=>{qa.calls.push({kind:'image-upload',dataUrl,crop});return '22222222-2222-4222-8222-222222222222';},
  cloudShopOperation:async operation=>{qa.calls.push({kind:'shop-operation',operation});const next=clone(qa.document);if(operation.type==='shop-image')next.inventory.items[operation.barcode].shop.imageId=operation.imageId;else for(const barcode of operation.barcodes)next.inventory.items[barcode].listed=operation.listed;return save(next);},
  updatePrice:async(barcode,purchase,sale,currency)=>{qa.calls.push({kind:'card-price',barcode,purchase,sale,currency});const next=clone(qa.document),item=next.inventory.items[barcode];Object.assign(item,{priceAmount:purchase,salePriceAmount:sale,priceCurrency:currency});if(currency==='CAD'&&sale!==null)item.shop={...item.shop,originalCents:Math.max(item.shop.originalCents,Math.round(sale*100)),currentCents:Math.round(sale*100),priceSource:'current'};return save(next);}
 };
});
try{
 await page.goto(origin);const card=page.locator('[data-item-barcode="123"]'),shop=card.locator('.shop-editor');await card.waitFor();await shop.locator('summary').click();
 const original=shop.getByLabel('原价 CAD',{exact:true}),current=shop.getByLabel('现价 CAD',{exact:true}),save=shop.getByRole('button',{name:'保存商店价格',exact:true});
 await original.fill('');await page.evaluate(()=>window.qa.emit({quantityOnHand:11}));assert.equal(await original.inputValue(),'');assert.ok(await save.isDisabled());await shop.getByText('请输入原价。',{exact:true}).waitFor();check('empty shop draft survives unrelated refresh and cannot silently save zero');
 assert.ok(await shop.getByRole('checkbox').isDisabled());await shop.getByText('请先保存或放弃价格修改，再首次上架注册。').waitFor();check('first listing waits for an unsaved price draft to be saved or discarded');
 await original.fill('25');await current.fill('12.50');await page.evaluate(()=>window.qa.emit({shop:{...window.qa.document.inventory.items['123'].shop,imageId:'33333333-3333-4333-8333-333333333333'}}));assert.equal(await current.inputValue(),'12.50');assert.equal(await shop.locator('.shop-price-conflict').count(),0);await save.click();await shop.getByText('商店价格已保存到本地，等待云同步。').waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.at(-1).shop.imageId),'33333333-3333-4333-8333-333333333333');check('price save uses latest imageId and says locally saved awaiting sync');
 await page.evaluate(()=>window.qa.fail=true);await current.fill('13');await save.click();await shop.getByRole('alert').waitFor();assert.equal(await current.inputValue(),'13');assert.ok(!await shop.getByText('商店价格已保存到本地，等待云同步。').count());check('failed save retains input and does not claim shop publication');
 await page.evaluate(()=>{window.qa.fail=false;window.qa.emit({shop:{...window.qa.document.inventory.items['123'].shop,originalCents:3000,currentCents:1800,discountBps:4000},salePriceAmount:18});});await shop.locator('.shop-price-conflict').waitFor();assert.equal(await current.inputValue(),'13');assert.ok(await save.isDisabled());await page.screenshot({path:path.join(output,'shop-conflict.png'),fullPage:true});report.screenshots.push('shop-conflict.png');await shop.getByRole('button',{name:'保留草稿继续编辑'}).click();assert.ok(await save.isEnabled());await save.click();await shop.getByText('商店价格已保存到本地，等待云同步。').waitFor();check('external price conflict blocks save, keeps draft, and explicit acknowledgement permits save');
 await current.fill('14');await page.evaluate(()=>window.qa.emit({shop:{...window.qa.document.inventory.items['123'].shop,currentCents:1700},salePriceAmount:17}));await shop.getByRole('button',{name:'重新载入价格'}).click();assert.equal(await current.inputValue(),'17.00');check('reload explicitly adopts latest persisted price');
 await current.fill('11.11');await shop.getByRole('button',{name:'移除商店图片'}).click();await shop.getByRole('button',{name:'保存主图',exact:true}).click();await shop.getByText(/主图已保存到云端库存/).waitFor();assert.equal(await current.inputValue(),'11.11');assert.equal(await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.currentCents),1700);assert.deepEqual(await page.evaluate(()=>window.qa.calls.at(-1).operation),{type:'shop-image',barcode:'123',imageId:null});check('image removal uses an explicit image-only operation and preserves unsaved price draft');
 await shop.getByRole('button',{name:'选择并裁切自有图片'}).click();await shop.getByRole('button',{name:'裁切并上传图片'}).click();await shop.getByText(/裁切图已上传/).waitFor();assert.equal(await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.imageId),null);await shop.getByRole('button',{name:'保存主图',exact:true}).click();await shop.getByText(/主图已保存到云端库存/).waitFor();assert.equal(await current.inputValue(),'11.11');assert.equal(await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.currentCents),1700);check('image upload requires explicit save and never submits a price draft');
 await page.evaluate(()=>window.qa.cloudEmit({registeredBarcodes:['123']}));await shop.getByText(/已在网页商店注册/).waitFor();assert.ok(await shop.getByRole('checkbox').isEnabled());assert.ok(await shop.getByRole('button',{name:'选择并裁切自有图片'}).isEnabled());assert.ok(await save.isEnabled());check('registered products allow listing and image management while CAD prices remain editable');
 await shop.getByRole('button',{name:'放弃价格修改'}).click();const sale=card.locator('.price-row').getByLabel('售价',{exact:true});await sale.fill('19.25');const before=await page.evaluate(()=>window.qa.calls.length);await page.evaluate(()=>window.qa.emit({shop:{...window.qa.document.inventory.items['123'].shop,currentCents:2000},salePriceAmount:20}));await card.locator('.card-price-draft').getByText(/价格记录已变化/).waitFor();assert.equal(await sale.inputValue(),'19.25');await sale.blur();assert.equal(await page.evaluate(()=>window.qa.calls.length),before);check('card draft survives external CAD price change and blur cannot overwrite it');
 await card.locator('.card-price-draft').getByRole('button',{name:'保留草稿继续编辑'}).click();await sale.focus();await sale.blur();assert.equal(await page.evaluate(()=>window.qa.calls.length),before);await card.locator('.card-price-draft').getByRole('button',{name:'保存价格',exact:true}).click();await page.getByText('已保存到本地；已连接库存将自动同步商店。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.at(-1).sale),19.25);check('keeping a card conflict requires explicit save; success describes local persistence');
 await sale.fill('bad');const invalidBefore=await page.evaluate(()=>window.qa.calls.length);await sale.blur();await page.getByText(/售价须为非负数字/).waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.length),invalidBefore);check('invalid card text is rejected rather than converted to null or zero');
 await page.evaluate(()=>window.qa.switchFile());await page.waitForFunction(()=>document.querySelector('.file-strip')?.textContent?.includes('second.json'));assert.equal(await sale.inputValue(),'15');await shop.locator('summary').click();assert.equal(await current.inputValue(),'15.00');assert.ok(await shop.getByRole('checkbox').isEnabled());assert.equal(await card.locator('.card-price-draft').count(),0);check('file identity resets both drafts and ignores previous file registration status');
 await current.fill('12');await page.evaluate(()=>window.qa.defer=true);await save.click();await page.waitForFunction(()=>typeof window.qa.pending==='function');await page.evaluate(()=>{window.qa.document.filePath='C:/synthetic/third.json';window.qa.document.fileName='third.json';window.qa.document.inventory.inventoryId='third';window.qa.emit({salePriceAmount:22,shop:{...window.qa.document.inventory.items['123'].shop,currentCents:2200,originalCents:2500}});});await page.waitForFunction(()=>document.querySelector('.file-strip')?.textContent?.includes('third.json'));await page.evaluate(()=>window.qa.pending());await page.waitForTimeout(100);assert.equal(await sale.inputValue(),'22');await shop.locator('summary').click();assert.equal(await current.inputValue(),'22.00');check('completion from an unmounted old file editor cannot replace the new document or draft');
 await page.evaluate(()=>window.qa.defer=false);const currency=card.locator('.price-row select');const shopBeforeCurrency=await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.currentCents);await currency.selectOption('JPY');await page.getByText('价格已保存到本地。货币标签已更新，未执行换汇。',{exact:true}).waitFor();assert.equal(await sale.inputValue(),'22');assert.equal(await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.currentCents),shopBeforeCurrency);await currency.selectOption('CAD');await page.getByText('价格已保存到本地。货币标签已更新，未执行换汇。',{exact:true}).waitFor();check('currency changes retain numeric value and do not claim conversion or shop synchronization');
 await sale.fill('');await sale.blur();await page.getByText('价格已保存到本地。售价未定价，不会将商店商品改为免费。',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.qa.calls.at(-1).sale),null);assert.equal(await page.evaluate(()=>window.qa.document.inventory.items['123'].shop.currentCents),shopBeforeCurrency);check('empty card sale stays unpriced and does not change the shop to free');
 await current.fill('21');await page.evaluate(()=>scrollTo(0,450));const shopAnchor=await card.evaluate(n=>n.getBoundingClientRect().top);await save.evaluate(n=>n.click());await shop.getByText('商店价格已保存到本地，等待云同步。').waitFor();await page.waitForTimeout(80);assert.ok(Math.abs(await card.evaluate(n=>n.getBoundingClientRect().top)-shopAnchor)<2);check('shop price save preserves the edited card scroll anchor');
 await sale.fill('20.50');await page.evaluate(()=>scrollTo(0,450));const cardAnchor=await card.evaluate(n=>n.getBoundingClientRect().top);await sale.evaluate(n=>n.blur());await page.getByText('已保存到本地；已连接库存将自动同步商店。',{exact:true}).waitFor();await page.waitForTimeout(80);assert.ok(Math.abs(await card.evaluate(n=>n.getBoundingClientRect().top)-cardAnchor)<2);check('card price blur save preserves scroll anchor and does not focus barcode');
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,'final-desktop.png'),fullPage:true});report.screenshots.push('final-desktop.png');await page.setViewportSize({width:768,height:1000});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(output,'final-768.png'),fullPage:true});report.screenshots.push('final-768.png');await page.getByRole('button',{name:'深色',exact:true}).click();await page.screenshot({path:path.join(output,'final-dark-768.png'),fullPage:true});report.screenshots.push('final-dark-768.png');
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.blocked,[]);for(const row of sourceFiles)assert.equal(sha(await readFile(row.path)),row.sha256);report.sourceUnchanged=true;report.passed=true;
}catch(error){report.failure=error.stack;await page.screenshot({path:path.join(output,'failure.png')}).catch(()=>{});throw error;}
finally{await browser.close();await server.close();await writeFile(path.join(output,'report.json'),JSON.stringify(report,null,2)+'\n');console.log('REPORT '+output);}
